create table public.driver (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  email text null,
  password text null,
  name text null,
  avatar text null,
  dob text null,
  nin bigint null,
  phone text[] null,
  address text[] null,
  kyc boolean null,
  constraint agent_pkey primary key (id)
) TABLESPACE pg_default;

create table public.admins (
  id bigint generated by default as identity not null,
  email character varying(255) not null,
  role character varying(20) null default 'editor'::character varying,
  created_at timestamp with time zone null default now(),
  name text null,
  avatar text null,
  password text null,
  user_id uuid null,
  constraint admins_pkey primary key (id),
  constraint admins_email_key unique (email),
  constraint admins_user_id_key unique (user_id),
  constraint admins_role_check check (
    (
      (role)::text = any (
        array[
          ('admin'::character varying)::text,
          ('editor'::character varying)::text,
          ('viewer'::character varying)::text
        ]
      )
    )
  )
) TABLESPACE pg_default;

create table public.buses (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  bus_code text null,
  driver bigint null,
  letter boolean null,
  e_payment bigint null,
  contract_date date null,
  agreed_date date null,
  date_collected date null,
  start_date date null,
  first_pay date null,
  initial_owe bigint null,
  deposited bigint null,
  t_income bigint null,
  plate_no text null,
  coordinator bigint null,
  constraint buses_pkey primary key (id),
  constraint buses_coordinator_fkey foreign KEY (coordinator) references coordinators (id) on delete set null,
  constraint buses_driver_fkey foreign KEY (driver) references driver (id) on update CASCADE on delete set null
) TABLESPACE pg_default;

create table public.payment (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  week date null,
  coordinator text null,
  user_id uuid null default gen_random_uuid (),
  bus bigint null,
  p_week text null,
  receipt text null,
  amount bigint null,
  sender text null,
  payment_day text null,
  payment_date date null,
  pay_type text null,
  pay_complete boolean null,
  issue text null,
  inspection boolean null,
  constraint payment_pkey primary key (id),
  constraint payment_user_id_fkey foreign KEY (user_id) references users (id) on update CASCADE on delete set null
) TABLESPACE pg_default;

create table public.coordinators (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  email text null,
  password text null,
  name text null,
  avatar text null,
  phone text[] null,
  constraint coordinator_pkey primary key (id)
) TABLESPACE pg_default;

create table public.payment (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  week date null,
  coordinator text null,
  bus bigint null,
  p_week text null,
  receipt text null,
  amount bigint null,
  sender text null,
  payment_day text null,
  payment_date date null,
  pay_type text null,
  pay_complete boolean null,
  issue text null,
  inspection boolean null,
  constraint payment_pkey primary key (id),
  constraint payment_bus_fkey foreign KEY (bus) references buses (id) on delete set null
) TABLESPACE pg_default;

INSERT INTO "public"."admins" ("id", "email", "role", "created_at", "name", "avatar", "password", "user_id") VALUES ('1', 'admin@annhurst.com', 'admin', '2025-09-06 19:05:45+00', 'Administrator', null, '123', null);

INSERT INTO "public"."coordinators" ("id", "created_at", "email", "password", "name", "avatar", "phone", "user_id") VALUES ('1', '2025-09-03 21:04:44+00', 'chuksmanny97@gmail.com', '123', 'Emmanuel', null, '"{\"09054257289\"]}', '8f05ba64-005d-4c56-b426-3badd4596c0f'), ('2', '2025-09-03 21:09:27+00', 'abisomukailaabiso@gmail.com', '123', 'Mukaila', null, '"{\"09063750685\"]}', '646ee4e2-f49f-4789-bb75-0bec72a64d60'), ('3', '2025-09-03 21:11:16+00', 'rolandogbaisi75@gmail.com', '123', 'Roland', null, '"{\"08122574825\"]}', 'd74e5de5-02e4-4bd1-9249-92ca931012f5'), ('4', '2025-09-03 21:12:50+00', 'cereoah@annhurst-gsl.com', '123', 'Cleophas', null, '"{\"07065226741\"]}', '1a145b44-0dc3-41d1-b024-36fbca710578');

INSERT INTO "public"."driver" ("id", "created_at", "email", "password", "name", "avatar", "dob", "nin", "phone", "address", "kyc", "user_id") VALUES ('1', '2025-09-02 13:43:03.089671+00', 'taiwo@annhurst-gsl.com', '123456', 'Taiwo Tola Seun', null, '1990-01-01', '1234567890', '"{\"08164645709\",\"09116140644\"]}', '"{\"   \\t AGBEDE TRANSFORMER, LAST BUS STOP, BALE OLOMI HOUSE, OFF AGRIC, IKORODU, LAGOS\"]}', 'true', 'a5448f37-a4d5-4d84-b8b4-9d235fd3b4b8'), ('2', '2025-09-03 11:27:20.646577+00', 'oladayo@annhurst-gsl.com', '123456', 'OLADAYO CHRISTOPHER SUNDAY', null, '1990-01-02', '1234567890', '"{\"09038065002\"]}', '"{\"4, TRANSIT VILLAGE, ADETOKUNBO ADEMOLA, VICTORIA ISLAND\"]}', 'false', 'fb832cfb-4ac3-4083-ad41-e39034263c5c'), ('3', '2025-09-03 15:38:43.477276+00', 'essien@annhurst-gsl.com', '123456', 'ESSIEN ELIZABETH', null, '1990-01-04', '12345678901', '"{\"08056311132\",\"08065095594\"]}', '"{\"PLOT 23, RD 13, LEKKI ATLANTIC GARDEN ESTATE, AJAH, LAGOS\",\"PLOT 35, RD 13, LEKKI ATLANTIC GARDEN ESTATE, AJAH LAGOS STATE\"]}', 'false', 'c476d91b-0ea8-436d-a923-550c05f078df');

INSERT INTO "public"."buses" ("id", "created_at", "bus_code", "driver", "letter", "e_payment", "contract_date", "agreed_date", "date_collected", "start_date", "first_pay", "initial_owe", "deposited", "t_income", "plate_no", "coordinator") VALUES ('1', '2025-09-03 15:53:51+00', 'L07', '3', 'false', '60000', '2025-04-07', '2027-01-03', '2025-04-12', '2025-04-14', '2025-04-20', '5600000', '100000', '2250000', 'KTU 724 YK', '4'), ('3', '2025-09-03 16:40:53+00', 'M01', '2', 'false', '65000', '2025-06-20', '2027-03-14', '2025-07-11', '2025-07-14', '2025-07-20', '5863000', '65000', '718000', 'KTU 211 YL', '1'), ('4', '2025-09-03 16:46:19+00', 'L08', '1', 'false', '60000', '2025-04-07', '2027-01-03', '2025-04-12', '2025-04-14', '2025-04-20', '5600000', '60000', '2250000', 'KTU 725 YK', '4');