create table public.driver (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  email text null,
  password text null,
  name text null,
  avatar text null,
  dob text null,
  nin bigint null,
  phone text[] null,
  address text[] null,
  kyc boolean null,
  constraint agent_pkey primary key (id)
) TABLESPACE pg_default;

create table public.users (
  id uuid not null default gen_random_uuid (),
  email character varying(255) not null,
  role character varying(20) null default 'user'::character varying,
  created_at timestamp with time zone null default now(),
  name text null,
  avatar text null,
  constraint users_pkey primary key (id),
  constraint users_email_key unique (email),
  constraint users_role_check check (
    (
      (role)::text = any (
        (
          array[
            'admin'::character varying,
            'user'::character varying,
            'driver'::character varying
          ]
        )::text[]
      )
    )
  )
) TABLESPACE pg_default;