create table public.driver (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  email text null,
  password text null,
  name text null,
  avatar text null,
  dob text null,
  nin bigint null,
  phone text[] null,
  address text[] null,
  kyc boolean null,
  constraint agent_pkey primary key (id)
) TABLESPACE pg_default;

create table public.users (
  id uuid not null default gen_random_uuid (),
  email character varying(255) not null,
  role character varying(20) null default 'user'::character varying,
  created_at timestamp with time zone null default now(),
  name text null,
  avatar text null,
  constraint users_pkey primary key (id),
  constraint users_email_key unique (email),
  constraint users_role_check check (
    (
      (role)::text = any (
        array[
          ('admin'::character varying)::text,
          ('user'::character varying)::text,
          ('driver'::character varying)::text
        ]
      )
    )
  )
) TABLESPACE pg_default;

create table public.buses (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  bus_code text null,
  driver bigint null,
  letter boolean null,
  e_payment bigint null,
  contract_date date null,
  agreed_date date null,
  date_collected date null,
  start_date date null,
  first_pay date null,
  initial_owe bigint null,
  deposited bigint null,
  t_income bigint null,
  plate_no text null,
  coordinator bigint null,
  constraint buses_pkey primary key (id),
  constraint buses_coordinator_fkey foreign KEY (coordinator) references coordinators (id) on delete set null,
  constraint buses_driver_fkey foreign KEY (driver) references driver (id) on update CASCADE on delete set null
) TABLESPACE pg_default;

create table public.payment (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  week date null,
  coordinator text null,
  user_id uuid null default gen_random_uuid (),
  bus bigint null,
  p_week text null,
  receipt text null,
  amount bigint null,
  sender text null,
  payment_day text null,
  payment_date date null,
  pay_type text null,
  pay_complete boolean null,
  issue text null,
  inspection boolean null,
  constraint payment_pkey primary key (id),
  constraint payment_user_id_fkey foreign KEY (user_id) references users (id) on update CASCADE on delete set null
) TABLESPACE pg_default;

create table public.coordinators (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  email text null,
  password text null,
  name text null,
  avatar text null,
  phone text[] null,
  constraint coordinator_pkey primary key (id)
) TABLESPACE pg_default;

INSERT INTO "public"."coordinators" ("id", "created_at", "email", "password", "name", "avatar", "phone") VALUES ('1', '2025-09-03 21:04:44+00', 'chuksmanny97@gmail.com', '123', 'Emmanuel', null, '"{\"09054257289\"]}'), ('2', '2025-09-03 21:09:27+00', 'abisomukailaabiso@gmail.com', '123', 'Mukaila', null, '"{\"09063750685\"]}'), ('3', '2025-09-03 21:11:16+00', 'rolandogbaisi75@gmail.com', '123', 'Roland', null, '"{\"08122574825\"]}'), ('4', '2025-09-03 21:12:50+00', 'cereoah@annhurst-gsl.com', '123', 'Cleophas', null, '"{\"07065226741\"]}');

INSERT INTO "public"."driver" ("id", "created_at", "email", "password", "name", "avatar", "dob", "nin", "phone", "address", "kyc") VALUES ('1', '2025-09-02 13:43:03.089671+00', 'taiwo@annhurst-gsl.com', '123456', 'Taiwo Tola Seun', null, '1990-01-01', '1234567890', '"{\"08164645709\",\"09116140644\"]}', '"{\"   \\t AGBEDE TRANSFORMER, LAST BUS STOP, BALE OLOMI HOUSE, OFF AGRIC, IKORODU, LAGOS\"]}', 'true'), ('2', '2025-09-03 11:27:20.646577+00', 'oladayo@annhurst-gsl.com', '123456', 'OLADAYO CHRISTOPHER SUNDAY', null, '1990-01-02', '1234567890', '"{\"09038065002\"]}', '"{\"4, TRANSIT VILLAGE, ADETOKUNBO ADEMOLA, VICTORIA ISLAND\"]}', 'false'), ('3', '2025-09-03 15:38:43.477276+00', 'essien@annhurst-gsl.com', '123456', 'ESSIEN ELIZABETH', null, '1990-01-04', '12345678901', '"{\"08056311132\",\"08065095594\"]}', '"{\"PLOT 23, RD 13, LEKKI ATLANTIC GARDEN ESTATE, AJAH, LAGOS\",\"PLOT 35, RD 13, LEKKI ATLANTIC GARDEN ESTATE, AJAH LAGOS STATE\"]}', 'false');

INSERT INTO "public"."users" ("id", "email", "role", "created_at", "name", "avatar") VALUES ('0010399b-3352-488c-9dfc-8b9feff9e5f6', 'taiwo@annhurst-gsl.com', 'driver', '2025-09-03 11:17:10+00', 'Taiwo Tola Seun', null), ('0291a216-c8fc-4c03-8258-f8ecaf1d7f22', 'chuksmanny97@gmail.com', 'user', '2025-09-03 15:49:30+00', 'Emmanuel', null), ('6ae2c291-f1da-4420-b708-c8b21ae8d1f3', 'admin@annhurst.com', 'admin', '2025-08-12 01:25:38.91574+00', 'Administrator', null), ('74ff971d-1fb1-43a5-a41e-4470c39a08c8', 'abisomukailaabiso@gmail.com', 'user', '2025-09-03 15:53:27+00', 'Mukaila', null), ('925a3e9c-264e-48ce-bb9e-4f0935c3ef85', 'oladayo@annhurst-gsl.com', 'driver', '2025-09-03 11:27:21.206763+00', 'OLADAYO CHRISTOPHER SUNDAY', null), ('95967251-32f7-4553-a22d-6f3aaeaf8b0a', 'rolandogbaisi75@gmail.com', 'user', '2025-09-03 15:47:26+00', 'Roland', null), ('bffc871e-08c4-4182-93b6-e6cedd158ee7', 'essien@annhurst-gsl.com', 'driver', '2025-09-03 15:38:44.101422+00', 'ESSIEN ELIZABETH', null), ('cffc614b-5b3f-4213-9646-1201121cec9f', 'cereoah@annhurst-gsl.com', 'user', '2025-09-03 15:50:46+00', 'Cleophas', null);

INSERT INTO "public"."buses" ("id", "created_at", "bus_code", "driver", "letter", "e_payment", "contract_date", "agreed_date", "date_collected", "start_date", "first_pay", "initial_owe", "deposited", "t_income", "plate_no", "coordinator") VALUES ('1', '2025-09-03 15:53:51+00', 'L07', '3', 'false', '60000', '2025-04-07', '2027-01-03', '2025-04-12', '2025-04-14', '2025-04-20', '5600000', '100000', '2250000', 'KTU 724 YK', '4'), ('3', '2025-09-03 16:40:53+00', 'M01', '2', 'false', '65000', '2025-06-20', '2027-03-14', '2025-07-11', '2025-07-14', '2025-07-20', '5863000', '65000', '718000', 'KTU 211 YL', '1'), ('4', '2025-09-03 16:46:19+00', 'L08', '1', 'false', '60000', '2025-04-07', '2027-01-03', '2025-04-12', '2025-04-14', '2025-04-20', '5600000', '60000', '2250000', 'KTU 725 YK', '4');